In [ ]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

NameError: name 'np' is not defined

In [ ]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,
                                                               array2.ndim, array3.ndim))

In [3]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>

NameError: name 'np' is not defined

In [4]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

NameError: name 'np' is not defined

In [5]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

NameError: name 'np' is not defined

In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

In [ ]:
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

In [6]:
array1=np.arange(10)
print('array1:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n', array2)

array3=array1.reshape(5,2)
print('array3:\n', array3)

NameError: name 'np' is not defined

In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:', array3.shape)

In [7]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

NameError: name 'np' is not defined

In [ ]:
array1=np.arange(start=1, stop=10)
print('array1:', array1)
value=array1[2]
print('value:', value)
print(type(value))

In [8]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])
array1[0] = 9
array1[8] = 0
print('array1:', array1)

NameError: name 'array1' is not defined

In [ ]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

In [9]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

NameError: name 'np' is not defined

In [ ]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

In [10]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]  \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]  \n', array2d[1:3, 0:3])
print('array2d[1:3, :]  \n', array2d[1:3, :])
print('array2d[:, :]  \n', array2d[:, :])
print('array2d[:2, 1:]  \n', array2d[:2, 1:])
print('array2d[:2, 0]  \n', array2d[:2, 0])

NameError: name 'np' is not defined

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

In [11]:
array1d = np.arange(start=1, stop=10)
array2d= array1d.reshape(3,3)

array3=array2d[[0,1], 2]
print('array2d[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>',array5.tolist())

NameError: name 'np' is not defined

In [12]:
array1d=np.arange(start=1, stop=10)
# []안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)
array1d>5

NameError: name 'np' is not defined

In [ ]:
boolean_indexes=np.array([False, False, False, False, False, True, True, True, True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

In [13]:
indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

NameError: name 'np' is not defined

In [ ]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

In [14]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)
array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

NameError: name 'np' is not defined

In [ ]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

In [ ]:
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

In [15]:
import numpy as np
import pandas as pd

col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
df_list1=pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
df_array1=pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [1]:
import numpy as np
import pandas as pd

#3개의 칼럼명이 필요함.
col_name2=['col1', 'col2', 'col3']

list2=[[1,2,3],
       [11,12,13]]
array2=np.array(list2)
df_list2=pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2=pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

NameError: name 'np' is not defined

In [16]:
dict={'col1':[1,11  ], 'col2':[2,22], 'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

In [17]:
array3=df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [18]:
list3=df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

dict3=df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [29]:
pd.read_csv('titanic_train.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
titanic_df = pd.read_csv('titanic_train.csv')
titanic_df['Age_0']=0
titanic_df.head(3)

titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [32]:
titanic_drop_df=titanic_df.drop('Age_0', axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,260.0,1

In [33]:
drop_result=titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop 후 반환된 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 반환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [37]:
titanic_df=pd.read_csv('titanic_train.csv')
indices=titanic_df[titanic_df['Age']>60].index
print('열향식 조건식 인덱스 객체의 전체 데이터:', indices)
print(titanic_df['Name'].head(3))

titanic_reset_df=titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

열향식 조건식 인덱스 객체의 전체 데이터: Index([ 33,  54,  96, 116, 170, 252, 275, 280, 326, 438, 456, 483, 493, 545,
       555, 570, 625, 630, 672, 745, 829, 851],
      dtype='int64')
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
Name: Name, dtype: object

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [38]:
titanic_sorted=titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.55,NaN,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.25,NaN,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.25,NaN,S

In [39]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [40]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [41]:
titanic_groupby=titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [42]:
titanic_groupby=titanic_df.groupby('Pclass').count()
titanic_groupby

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

In [43]:
titanic_groupby=titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [44]:
titanic_df.groupby('Pclass')['Age'].agg([max,min])

/tmp/ipykernel_7573/414103430.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])
/tmp/ipykernel_7573/414103430.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('Pclass')['Age'].agg([max,min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [ ]:
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

In [45]:
titanic_df.isna().head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False

In [46]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [47]:
titanic_df['Cabin']=titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C000,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C000,S

In [48]:
titanic_df['Age']=titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [50]:
def get_square(a):
  return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [51]:
lambda_square=lambda x : x**2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9

In [52]:
a=[1,2,3]
squares=map(lambda x: x**2, a)
list(squares)

[1, 4, 9]

In [54]:
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x:len(x))
titanic_df[['Name', 'Name_len']].head(3)

                                                Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22